/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type MenuCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "menuCategory";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type MenuItem = {
  _id: string;
  _type: "menuItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category: MenuCategoryReference;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  description: string;
  rating: number;
  orderUrl: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type MenuCategory = {
  _id: string;
  _type: "menuCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label: string;
  slug: Slug;
  icon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  homeRow: "top" | "bottom" | "none";
  homeOrder?: number;
  menuOrder?: number;
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  footerLabel: string;
  phrase: string;
  displayOrder: number;
  cardImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }>;
  overviewParagraphs: Array<string>;
  overviewHighlight: string;
  overviewBullets?: Array<string>;
  address: string;
  phone: string;
  email: string;
  openedDay: string;
  hours: Array<{
    day: "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat" | "Sun";
    time: string;
    _type: "hoursEntry";
    _key: string;
  }>;
  guruUrl: string;
  badgeName: string;
  mapEmbedUrl: string;
  mapTitle: string;
  mapTagline: string;
  metaTitle: string;
  metaDescription: string;
};

export type HeroSlide = {
  _id: string;
  _type: "heroSlide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  alt: string;
  desktopImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mobileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  displayOrder: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | MenuCategoryReference
  | SanityImageAssetReference
  | MenuItem
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | MenuCategory
  | Location
  | HeroSlide
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/sanity/queries.ts
// Variable: HOME_MENU_CATEGORIES_QUERY
// Query: *[_type == "menuCategory" && homeRow != "none" && defined(slug.current)]    | order(homeRow asc, homeOrder asc, label asc) {      _id,      "slug": slug.current,      label,      homeRow,      icon {  asset->{_id, _type},  hotspot,  crop,  alt}    }
export type HOME_MENU_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  slug: string;
  label: string;
  homeRow: "bottom" | "none" | "top";
  icon: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  };
}>;

// Source: src/lib/sanity/queries.ts
// Variable: MENU_CATEGORIES_QUERY
// Query: *[_type == "menuCategory" && defined(slug.current)]    | order(menuOrder asc, label asc) {      _id,      "slug": slug.current,      label,      image {  asset->{_id, _type},  hotspot,  crop,  alt}    }
export type MENU_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  slug: string;
  label: string;
  image: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  };
}>;

// Source: src/lib/sanity/queries.ts
// Variable: MENU_CATEGORY_PAGE_QUERY
// Query: *[_type == "menuCategory" && slug.current == $slug][0] {    _id,    "slug": slug.current,    label,    "items": *[_type == "menuItem"      && category._ref == ^._id      && defined(slug.current)] | order(title asc) {        _id,        "slug": slug.current,        title,        image {  asset->{_id, _type},  hotspot,  crop,  alt}      }  }
export type MENU_CATEGORY_PAGE_QUERY_RESULT = {
  _id: string;
  slug: string;
  label: string;
  items: Array<{
    _id: string;
    slug: string;
    title: string;
    image: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
      } | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string;
    };
  }>;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: MENU_CATEGORY_SLUGS_QUERY
// Query: *[_type == "menuCategory" && defined(slug.current)]{    "slug": slug.current  }
export type MENU_CATEGORY_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: MENU_ITEM_PAGE_QUERY
// Query: *[_type == "menuItem"    && slug.current == $itemSlug    && category._ref in *[_type == "menuCategory" && slug.current == $categorySlug]._id][0] {      _id,      "slug": slug.current,      title,      description,      rating,      orderUrl,      image {  asset->{_id, _type},  hotspot,  crop,  alt},      "category": category->{        _id,        "slug": slug.current,        label      }    }
export type MENU_ITEM_PAGE_QUERY_RESULT = {
  _id: string;
  slug: string;
  title: string;
  description: string;
  rating: number;
  orderUrl: string;
  image: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  };
  category: {
    _id: string;
    slug: string;
    label: string;
  };
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: MENU_ITEM_SLUGS_QUERY
// Query: *[_type == "menuItem"    && defined(slug.current)    && defined(category->slug.current)] {      "slug": slug.current,      "categorySlug": category->slug.current    }
export type MENU_ITEM_SLUGS_QUERY_RESULT = Array<{
  slug: string;
  categorySlug: string;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: HERO_SLIDES_QUERY
// Query: *[_type == "heroSlide"] | order(displayOrder asc) {    _id,    alt,    "desktopImage": desktopImage{asset->{_id, _type}, hotspot, crop},    "mobileImage": mobileImage{asset->{_id, _type}, hotspot, crop}  }
export type HERO_SLIDES_QUERY_RESULT = Array<{
  _id: string;
  alt: string;
  desktopImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  mobileImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
}>;

// Source: src/lib/sanity/queries.ts
// Variable: LOCATIONS_NAV_QUERY
// Query: *[_type == "location" && defined(slug.current)]    | order(displayOrder asc, title asc) {      _id,      "slug": slug.current,      title,      footerLabel    }
export type LOCATIONS_NAV_QUERY_RESULT = Array<{
  _id: string;
  slug: string;
  title: string;
  footerLabel: string;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: HOME_STORES_QUERY
// Query: *[_type == "location" && defined(slug.current)]    | order(displayOrder asc, title asc) {      _id,      "slug": slug.current,      title,      address,      phone,      badgeName,      guruUrl,      cardImage {  asset->{_id, _type},  hotspot,  crop,  alt}    }
export type HOME_STORES_QUERY_RESULT = Array<{
  _id: string;
  slug: string;
  title: string;
  address: string;
  phone: string;
  badgeName: string;
  guruUrl: string;
  cardImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  };
}>;

// Source: src/lib/sanity/queries.ts
// Variable: LOCATION_PAGE_QUERY
// Query: *[_type == "location" && slug.current == $slug][0] {    _id,    "slug": slug.current,    title,    phrase,    address,    phone,    email,    openedDay,    badgeName,    guruUrl,    mapEmbedUrl,    mapTitle,    mapTagline,    metaTitle,    metaDescription,    overviewParagraphs,    overviewHighlight,    overviewBullets,    hours[]{_key, day, time},    gallery[]{      _key,      asset->{_id, _type},      hotspot,      crop,      alt    }  }
export type LOCATION_PAGE_QUERY_RESULT = {
  _id: string;
  slug: string;
  title: string;
  phrase: string;
  address: string;
  phone: string;
  email: string;
  openedDay: string;
  badgeName: string;
  guruUrl: string;
  mapEmbedUrl: string;
  mapTitle: string;
  mapTagline: string;
  metaTitle: string;
  metaDescription: string;
  overviewParagraphs: Array<string>;
  overviewHighlight: string;
  overviewBullets: Array<string> | null;
  hours: Array<{
    _key: string;
    day: "Fri" | "Mon" | "Sat" | "Sun" | "Thu" | "Tue" | "Wed";
    time: string;
  }>;
  gallery: Array<{
    _key: string;
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  }>;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: LOCATION_SLUGS_QUERY
// Query: *[_type == "location" && defined(slug.current)]{    "slug": slug.current  }
export type LOCATION_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "menuCategory" && homeRow != "none" && defined(slug.current)]\n    | order(homeRow asc, homeOrder asc, label asc) {\n      _id,\n      "slug": slug.current,\n      label,\n      homeRow,\n      icon {\n  asset->{_id, _type},\n  hotspot,\n  crop,\n  alt\n}\n    }\n': HOME_MENU_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "menuCategory" && defined(slug.current)]\n    | order(menuOrder asc, label asc) {\n      _id,\n      "slug": slug.current,\n      label,\n      image {\n  asset->{_id, _type},\n  hotspot,\n  crop,\n  alt\n}\n    }\n': MENU_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "menuCategory" && slug.current == $slug][0] {\n    _id,\n    "slug": slug.current,\n    label,\n    "items": *[_type == "menuItem"\n      && category._ref == ^._id\n      && defined(slug.current)] | order(title asc) {\n        _id,\n        "slug": slug.current,\n        title,\n        image {\n  asset->{_id, _type},\n  hotspot,\n  crop,\n  alt\n}\n      }\n  }\n': MENU_CATEGORY_PAGE_QUERY_RESULT;
    '\n  *[_type == "menuCategory" && defined(slug.current)]{\n    "slug": slug.current\n  }\n': MENU_CATEGORY_SLUGS_QUERY_RESULT;
    '\n  *[_type == "menuItem"\n    && slug.current == $itemSlug\n    && category._ref in *[_type == "menuCategory" && slug.current == $categorySlug]._id][0] {\n      _id,\n      "slug": slug.current,\n      title,\n      description,\n      rating,\n      orderUrl,\n      image {\n  asset->{_id, _type},\n  hotspot,\n  crop,\n  alt\n},\n      "category": category->{\n        _id,\n        "slug": slug.current,\n        label\n      }\n    }\n': MENU_ITEM_PAGE_QUERY_RESULT;
    '\n  *[_type == "menuItem"\n    && defined(slug.current)\n    && defined(category->slug.current)] {\n      "slug": slug.current,\n      "categorySlug": category->slug.current\n    }\n': MENU_ITEM_SLUGS_QUERY_RESULT;
    '\n  *[_type == "heroSlide"] | order(displayOrder asc) {\n    _id,\n    alt,\n    "desktopImage": desktopImage{asset->{_id, _type}, hotspot, crop},\n    "mobileImage": mobileImage{asset->{_id, _type}, hotspot, crop}\n  }\n': HERO_SLIDES_QUERY_RESULT;
    '\n  *[_type == "location" && defined(slug.current)]\n    | order(displayOrder asc, title asc) {\n      _id,\n      "slug": slug.current,\n      title,\n      footerLabel\n    }\n': LOCATIONS_NAV_QUERY_RESULT;
    '\n  *[_type == "location" && defined(slug.current)]\n    | order(displayOrder asc, title asc) {\n      _id,\n      "slug": slug.current,\n      title,\n      address,\n      phone,\n      badgeName,\n      guruUrl,\n      cardImage {\n  asset->{_id, _type},\n  hotspot,\n  crop,\n  alt\n}\n    }\n': HOME_STORES_QUERY_RESULT;
    '\n  *[_type == "location" && slug.current == $slug][0] {\n    _id,\n    "slug": slug.current,\n    title,\n    phrase,\n    address,\n    phone,\n    email,\n    openedDay,\n    badgeName,\n    guruUrl,\n    mapEmbedUrl,\n    mapTitle,\n    mapTagline,\n    metaTitle,\n    metaDescription,\n    overviewParagraphs,\n    overviewHighlight,\n    overviewBullets,\n    hours[]{_key, day, time},\n    gallery[]{\n      _key,\n      asset->{_id, _type},\n      hotspot,\n      crop,\n      alt\n    }\n  }\n': LOCATION_PAGE_QUERY_RESULT;
    '\n  *[_type == "location" && defined(slug.current)]{\n    "slug": slug.current\n  }\n': LOCATION_SLUGS_QUERY_RESULT;
  }
}
